// Defines Sequelize models for SQL fallback. Returned models have similar names to mongoose ones.
module.exports = async function init(sequelize) {
  const { DataTypes } = require('sequelize');

  // Users table
  const User = sequelize.define('User', {
    name: { type: DataTypes.STRING, allowNull: false },
    email: { type: DataTypes.STRING, allowNull: false, unique: true },
    passwordHash: { type: DataTypes.STRING, allowNull: false },
    role: { type: DataTypes.STRING, defaultValue: 'user' },
    themePreference: { type: DataTypes.STRING, defaultValue: 'light' }
  });

  // Projects (was missing in SQL mode; project routes were broken)
  const Project = sequelize.define('Project', {
    title: { type: DataTypes.STRING, allowNull: false },
    description: { type: DataTypes.TEXT },
    members: { type: DataTypes.JSON } // optional array of user ids
  });

  // RAG docs: file reference + ingestion state (NOT full text blobs)
  const RagDocument = sequelize.define('RagDocument', {
    filename: { type: DataTypes.STRING, allowNull: false },
    mimeType: { type: DataTypes.STRING },
    sizeBytes: { type: DataTypes.INTEGER },
    storagePath: { type: DataTypes.STRING, allowNull: false },
    projectId: { type: DataTypes.STRING, allowNull: false, defaultValue: 'default-rag-project' },
    ownerId: { type: DataTypes.INTEGER, allowNull: true }, // Explicitly add foreign key field
    ingestionStatus: { type: DataTypes.STRING, defaultValue: 'queued' }, // queued|ingesting|ingested|failed
    ingestionMeta: { type: DataTypes.JSON }
  });

  // Legacy PDF documents stored as plain text
  const PdfDocument = sequelize.define('PdfDocument', {
    filename: { type: DataTypes.STRING, allowNull: false },
    contentText: { type: DataTypes.TEXT('long') }
  });

  // Chat messages for legacy PDF conversations
  const ChatMessage = sequelize.define('ChatMessage', {
    role: { type: DataTypes.STRING }, // 'user' or 'assistant'
    message: { type: DataTypes.TEXT }
  });

  // Reports generated by the system
  const Report = sequelize.define('Report', {
    title: { type: DataTypes.STRING, allowNull: false },
    content: { type: DataTypes.TEXT }
  });

  const Setting = sequelize.define('Setting', {
    preferences: { type: DataTypes.JSON }
  });

  // Multi-modal data support: generic documents (CSV, JSON, text, PDF, etc.)
  const Document = sequelize.define('Document', {
    filename: { type: DataTypes.STRING, allowNull: false },
    fileType: { type: DataTypes.STRING }, // 'csv', 'json', 'pdf', 'text', 'excel'
    contentText: { type: DataTypes.TEXT('long') },
    metadata: { type: DataTypes.JSON }, // file size, upload date, data insights
    uploadedAt: { type: DataTypes.DATE, defaultValue: DataTypes.NOW }
  });

  // Analysis sessions: grouped conversations and analyses
  const AnalysisSession = sequelize.define('AnalysisSession', {
    title: { type: DataTypes.STRING, allowNull: false },
    description: { type: DataTypes.TEXT },
    mode: { type: DataTypes.STRING }, // 'data_analysis' or 'document_chat'
    status: { type: DataTypes.STRING, defaultValue: 'active' }, // 'active', 'archived'
    createdAt: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    updatedAt: { type: DataTypes.DATE, defaultValue: DataTypes.NOW }
  });

  // Memory system: conversation history and context
  const ConversationMessage = sequelize.define('ConversationMessage', {
    role: { type: DataTypes.STRING }, // 'user' or 'assistant'
    content: { type: DataTypes.TEXT },
    messageType: { type: DataTypes.STRING }, // 'text', 'query', 'analysis', 'chart'
    metadata: { type: DataTypes.JSON }, // token usage, model info, etc.
    timestamp: { type: DataTypes.DATE, defaultValue: DataTypes.NOW }
  });

  // Analytics results and charts
  const AnalysisResult = sequelize.define('AnalysisResult', {
    analysisType: { type: DataTypes.STRING }, // 'summary', 'trend', 'correlation', 'distribution'
    title: { type: DataTypes.STRING },
    description: { type: DataTypes.TEXT },
    chartType: { type: DataTypes.STRING }, // 'bar', 'line', 'pie', 'scatter'
    data: { type: DataTypes.JSON }, // chart data and configuration
    insights: { type: DataTypes.JSON }, // AI-generated insights
    createdAt: { type: DataTypes.DATE, defaultValue: DataTypes.NOW }
  });

  // Associations
  User.hasMany(Project, { foreignKey: 'ownerId' });
  Project.belongsTo(User, { as: 'owner', foreignKey: 'ownerId' });

  User.hasMany(RagDocument, { foreignKey: 'ownerId' });
  RagDocument.belongsTo(User, { as: 'owner', foreignKey: 'ownerId' });

  User.hasMany(PdfDocument, { foreignKey: 'ownerId' });
  PdfDocument.belongsTo(User, { as: 'owner', foreignKey: 'ownerId' });

  PdfDocument.hasMany(ChatMessage, { foreignKey: 'pdfId' });
  ChatMessage.belongsTo(PdfDocument, { foreignKey: 'pdfId' });

  User.hasMany(Report, { foreignKey: 'ownerId' });
  Report.belongsTo(User, { as: 'owner', foreignKey: 'ownerId' });

  User.hasOne(Setting);
  Setting.belongsTo(User);

  User.hasMany(Document, { foreignKey: 'ownerId' });
  Document.belongsTo(User, { as: 'owner', foreignKey: 'ownerId' });

  User.hasMany(AnalysisSession, { foreignKey: 'ownerId' });
  AnalysisSession.belongsTo(User, { as: 'owner', foreignKey: 'ownerId' });

  AnalysisSession.hasMany(Document, { foreignKey: 'sessionId' });
  Document.belongsTo(AnalysisSession, { foreignKey: 'sessionId' });

  AnalysisSession.hasMany(ConversationMessage, { foreignKey: 'sessionId' });
  ConversationMessage.belongsTo(AnalysisSession, { foreignKey: 'sessionId' });

  AnalysisSession.hasMany(AnalysisResult, { foreignKey: 'sessionId' });
  AnalysisResult.belongsTo(AnalysisSession, { foreignKey: 'sessionId' });

  await sequelize.sync();

  return {
    User,
    Project,
    RagDocument,
    PdfDocument,
    ChatMessage,
    Report,
    Setting,
    Document,
    AnalysisSession,
    ConversationMessage,
    AnalysisResult
  };
};
